### ISSUE TITLE
Multiple editors

### ISSUE THREAD

**Issue by Krato** [hinesboy/mavonEditor#11]
Hi! First thanks for your great work!

I want to to have multiple editors using bootstrap tabs, how can achieve it?

The first editor is working fine, but when I go to the second tab the double panel is not visible, just the first one.

![captura de pantalla 2017-06-15 a las 14 02 15](https://user-images.githubusercontent.com/74367/27180340-48b2a966-51d3-11e7-9160-53fa2681103e.png)

![captura de pantalla 2017-06-15 a las 14 01 12](https://user-images.githubusercontent.com/74367/27180318-337f0f62-51d3-11e7-802b-d07bb0d844e7.png)

As you can see in the second editor the preview div is not visible.

Thanks

**Comment by hinesboy** [comment]
Thanks for your feedback.
I tried it, both editors have double panel.
![9cx2 wietqiz6t mx 9uvh](https://user-images.githubusercontent.com/26454305/27187008-9b2d7ac4-521c-11e7-92d6-a639a82a26e2.png)

Your second editor does not have a single and double column icon ， whether it is your custom **toolbars** object when there is no **subfield** attribute.
![w 76n6id czsjlxv 287m](https://user-images.githubusercontent.com/26454305/27187101-d86684bc-521c-11e7-8957-0b8d574f6033.png)
But the multiple editors will cause problems with shortcut keys. 
the shortcut keys will affect all editors because the listening target is **document object**
